
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

climate:
- platform: generic_thermostat
  name: Salon
  heater: switch.fibaro_system_fgwpe_f_wall_plug_switch
  target_sensor: sensor.aeon_labs_zw100_multisensor_6_temperature


# Text to speech
tts:
- platform: google_translate



zwave:
  usb_path: /dev/ttyACM0

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
