---
- apt:
    name:
    - docker.io
    - socat
    - conntrack
  notify: docker

- name: Customize Docker config
  copy:
    src: files/docker/daemon.json
    dest: /etc/docker/daemon.json
  notify: docker

- name: CNI folder
  file:
    state: directory
    path: /opt/cni/bin
    recurse: true

- name: CNI download and extract
  unarchive: 
    src: https://github.com/containernetworking/plugins/releases/download/{{kubernetes_cni_version}}/cni-plugins-linux-amd64-{{kubernetes_cni_version}}.tgz
    dest: /opt/cni/bin
    remote_src: yes
    creates: /opt/cni/bin/bridge

- name: K3s download
  get_url: 
    url: https://github.com/k3s-io/k3s/releases/download/{{kubernetes_version}}+k3s1/k3s
    dest: /usr/local/bin/k3s-{{kubernetes_version}}
    mode: 0770
    force: no

# - name: CRICTL download
#   unarchive:
#     src: https://github.com/kubernetes-sigs/cri-tools/releases/download/{{kubernetes_version}}/crictl-{{kubernetes_version}}-linux-amd64.tar.gz
#     dest: /usr/local/bin/
#     remote_src: yes
#     creates: /usr/local/bin/crictl-{{kubernetes_version}}

# - name: CRICTL stat
#   stat: path=/usr/local/bin/crictl-{{kubernetes_version}}
#   register: crictl_stat

# - name: CRICTL move
#   command: mv /usr/local/bin/crictl /usr/local/bin/crictl-{{kubernetes_version}}
#   when: not crictl_stat.stat.exists

# - name: Download Kubernetes binaries
#   get_url: 
#     url: https://storage.googleapis.com/kubernetes-release/release/{{kubernetes_version}}/bin/linux/amd64/{{item}}
#     dest: /usr/local/bin/{{item}}-{{kubernetes_version}}
#     mode: 0770
#     force: no
#   with_items: 
#   - kubeadm
#   - kubelet
#   - kubectl

- name: Link Kubernetes & crictl binaries
  file: 
    state: link
    src:  /usr/local/bin/{{item}}-{{kubernetes_version}}
    dest: /usr/local/bin/{{item}}
  with_items: 
  - k3s
#   - kubeadm
#   - kubelet
#   - kubectl
#   - crictl

# - name: Kubelet SystemD unit
#   copy:
#     src: files/kubelet.service
#     dest: /etc/systemd/system/kubelet.service
#   notify: kubelet



  # kubeadm config images pull
  # kubeadm 
  # add dns names for jared.pentex.pl
  # use ipvs